name: Deploy Application

on:
  push:
    branches:
      - main    # 当推送到 main 分支时触发
  pull_request:
    branches:
      - main    # 当发起 pull request 时触发

jobs:
  build:
    runs-on: ubuntu-latest    # 使用 Ubuntu 操作系统的最新版本进行构建

    steps:
      # 获取代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'    # 你可以根据需要选择不同的 Node.js 版本

      # 安装依赖
      - name: Install dependencies
        run: npm install

      # 运行测试
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest    # 使用 Ubuntu 操作系统的最新版本进行部署

    steps:
      # 获取代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 安装依赖
      - name: Install dependencies
        run: npm install

      # 构建项目
      - name: Build project
        run: npm run build

      # 部署到服务器（例如，使用 rsync 部署到远程服务器）
      - name: Deploy to server
        env:
          HOST: ${{ secrets.HOST }}   # 设置环境变量，使用 GitHub Secrets 存储敏感信息
          USER: ${{ secrets.USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" | ssh-add - > /dev/null
          rsync -avz --delete --exclude '.git' ./ $USER@$HOST:/path/to/your/project/