name: Upload Files to GitHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests Flask pycryptodome

      - name: Run Flask App and Log Errors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -c "
import os
from app import app
try:
    app.run(host='0.0.0.0', port=5000)
except Exception as e:
    print(f'Error: {str(e)}')
    exit(1)  # Exit with an error code to mark the job as failed
          "